version: '2.1'

services:
  api:
    image: pingapi
    build: ./api
    tty: true
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
  bot:
    image: pingbot
    build: ./bot
    tty: true
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
    depends_on:
      - api
  mongo:
    container_name: mongo
    image: mongo    
    ports:
      - "27017:27017"